### ISSUE TITLE
Add support for sort keys

### ISSUE THREAD

**Issue by ryanblock** [smallwins/begin-data#3]
I'd like to be able to specify a sort key so I can return (paginated) results of a table in order without running a scan and processing results. Not huge news, I know! [Reference](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-sort-keys.html).

**Comment by brianleroux** [comment]
so, yes… finally arriving back at this. the big thing w so-called 'wide column' design is designing a keyspace for the queries you expect.  as an example, imagine a stream of blog posts:
```
await data.set([{
  table: 'news', 
  key: '2019-09-10-good-news-everybody',
  body: 'good news everybody'
}, {
  table: 'news', 
  key: '2019-06-10-good-news-everybody',
  body: 'old good news everybody'
}])

```

whats fun about this is basically the whole sort query hack rides on `begins_with`. so we need a syntax for that…and we have the perfect thing! keep in mind this doesn't save you from pagination but it does give you ordered results.

```
// all the news in 2019
let articles = await data.get({
  table: 'news', 
  begin: '2019'
})
```

**Comment by brianleroux** [comment]
supported!
