### ISSUE TITLE
Feat req: UI for Data

### ISSUE THREAD

**Issue by corysimmons** [smallwins/begin-data#47]
First of all, very cool project! 🎉 

I created the Todo CRUD example app and added some todos to it. Then I clicked the Data link in sidebar expecting to see a submenu with tables listed, then clicking the table would show a table of the data, but got this instead:

![image](https://user-images.githubusercontent.com/224636/75396067-a184f880-58c1-11ea-9dab-356d5429c0a2.png)

Any plans to add a web UI for the Data section?

**Comment by corysimmons** [comment]
Whoops just saw your Canny.

**Comment by kristoferjoseph** [comment]
Funny you should ask. 
We made a data view that should be rolling out ASAP.

**Comment by ryanblock** [comment]
One note: we do have a read view right now! Add some data to your Begin Data store, and you'll see it in the Data tab. R down, CUD coming soon!

**Comment by corysimmons** [comment]
@ryanblock Hmm. I don't see the Read view? I created a "BEGIN BASIC CRUD APP" from the template options, then added some Todos manually via the frontend.

They seem to persist to a db somewhere, but when I click the Data tab I see the screenshot above.
