### ISSUE TITLE
@architect/sandbox v4.xx breaks with @begin/2.0.1, and v3 is not released

### ISSUE THREAD

**Issue by lwcooper** [smallwins/begin-data#90]
I looked at the changelog for `@begin/data`, and it seems there is a dependency where `@architect/sandbox v4.xx` requires `@begin/data v3`, but v3.0 is not released to npm yet, or tagged in git

I am using `@architect/sandbox v3.7.4` in the mean time, but it took me quite a while to figure out why my app was breaking after upgrading to `@architect/sandbox v4`

**Comment by lwcooper** [comment]
@ryanblock sorry for not providing repro steps, thanks a bunch for the quick fix!

**Comment by ryanblock** [comment]
No thanks necessary, my bad, thanks for letting me know!
